greeting:
  message: "hello"
quarkus:
  http:
    port: 8080
  application:
    name: Markdown API
  datasource:
    username: postgres
    password: postgres
    db-kind: h2
    jdbc.url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1
  hibernate-orm:
    schema-management:
      strategy: drop-and-create
    packages: org.robert.pollum.entity