greeting:
  message: "hello"
quarkus:
  http:
    port: 8080
  application:
    name: Markdown API
  datasource:
    username: postgres
    password: postgres
    db-kind: h2
    jdbc: 
      driver: org.h2.Driver
      url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1
      max-size: 16
  hibernate-orm:
    schema-management:
      strategy: drop-and-create
    packages: org.robert.pollum
  flyway:
    enabled: true
    schemas: PUBLIC
    validate-at-start: true